/** The 9 Business Memory layers. Maps to bb_types.memory_layer. */
export const MemoryLayer = {
  APPROVAL_INTELLIGENCE:    'APPROVAL_INTELLIGENCE',
  EDIT_PATTERN_INTELLIGENCE:'EDIT_PATTERN_INTELLIGENCE',
  REJECTION_INTELLIGENCE:   'REJECTION_INTELLIGENCE',
  PERFORMANCE_INTELLIGENCE: 'PERFORMANCE_INTELLIGENCE',
  BUSINESS_EVOLUTION:       'BUSINESS_EVOLUTION',
  SEASONAL_CONTEXTUAL:      'SEASONAL_CONTEXTUAL',
  OFFER_INTELLIGENCE:       'OFFER_INTELLIGENCE',
  OUTCOME_INTELLIGENCE:     'OUTCOME_INTELLIGENCE',
  AUDIENCE_TEMPERATURE:     'AUDIENCE_TEMPERATURE',
} as const;
export type MemoryLayer = typeof MemoryLayer[keyof typeof MemoryLayer];
